/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI */

#ifndef _Included_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
#define _Included_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
 * Method:    nuitrack_DestroyDepthFramePtr
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_1CAPI_nuitrack_1DestroyDepthFramePtr
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
 * Method:    nuitrack_GetDepthFrameRows
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;)J
 */
JNIEXPORT jlong JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_1CAPI_nuitrack_1GetDepthFrameRows
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
 * Method:    nuitrack_GetDepthFrameCols
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;)J
 */
JNIEXPORT jlong JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_1CAPI_nuitrack_1GetDepthFrameCols
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
 * Method:    nuitrack_GetDepthFrameID
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;)J
 */
JNIEXPORT jlong JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_1CAPI_nuitrack_1GetDepthFrameID
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
 * Method:    nuitrack_GetDepthFrameTimestamp
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;)J
 */
JNIEXPORT jlong JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_1CAPI_nuitrack_1GetDepthFrameTimestamp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_CAPI
 * Method:    nuitrack_GetDepthFrameData
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;)[J
 */
JNIEXPORT jlongArray JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthFrame_1CAPI_nuitrack_1GetDepthFrameData
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
