/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NuitrackJavaWrapper_Native_NuitrackImport */

#ifndef _Included_NuitrackJavaWrapper_Native_NuitrackImport
#define _Included_NuitrackJavaWrapper_Native_NuitrackImport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_Initialize
 * Signature: ()LNuitrackJavaWrapper/Types/NuitrackException/Type;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1Initialize
  (JNIEnv *, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_InitializeFromConfig
 * Signature: (Ljava/lang/String;)LNuitrackJavaWrapper/Types/NuitrackException/Type;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1InitializeFromConfig
  (JNIEnv *, jobject, jstring);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_InitializeFromConfig_E
 * Signature: (Ljava/lang/String;Ljava/lang/Long;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1InitializeFromConfig_1E
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
