/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NuitrackJavaWrapper_Native_NuitrackImport */

#ifndef _Included_NuitrackJavaWrapper_Native_NuitrackImport
#define _Included_NuitrackJavaWrapper_Native_NuitrackImport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_Initialize
 * Signature: ()LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1Initialize
  (JNIEnv *, jclass);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_InitializeFromConfig
 * Signature: (Ljava/lang/String;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1InitializeFromConfig
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_InitializeFromConfig_E
 * Signature: (Ljava/lang/String;LNuitrackJavaWrapper/Native/Pointers/NuitrackErrorPtr;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1InitializeFromConfig_1E
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_SetConfigValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1SetConfigValue
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetConfigValue
 * Signature: (Ljava/lang/String;LNuitrackJavaWrapper/Native/ChangeableObject;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetConfigValue
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_Run
 * Signature: ()LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1Run
  (JNIEnv *, jclass);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_Update
 * Signature: ()LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1Update
  (JNIEnv *, jclass);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_SyncUpdate
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1SyncUpdate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_WaitSyncUpdate
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1WaitSyncUpdate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_Release
 * Signature: ()LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1Release
  (JNIEnv *, jclass);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetNuitrackModuleCanUpdate
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)Z
 */
JNIEXPORT jboolean JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetNuitrackModuleCanUpdate
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetNuitrackModuleTimestamp
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)J
 */
JNIEXPORT jlong JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetNuitrackModuleTimestamp
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetLicense
 * Signature: (LNuitrackJavaWrapper/Native/ChangeableObject;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetLicense
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetInstancesJsonData
 * Signature: (LNuitrackJavaWrapper/Native/ChangeableObject;LNuitrackJavaWrapper/Native/Pointers/NuitrackErrorPtr;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetInstancesJsonData
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetVersion
 * Signature: (LNuitrackJavaWrapper/Native/ChangeableObject;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetVersion
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetExceptionType
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetExceptionType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetExceptionMessage
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;LNuitrackJavaWrapper/Native/ChangeableObject;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetExceptionMessage
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetErrorType
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackErrorPtr;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetErrorType
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_GetErrorMessage
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackErrorPtr;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1GetErrorMessage
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport
 * Method:    nuitrack_DestroyError
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackErrorPtr;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_nuitrack_1DestroyError
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
