/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI */

#ifndef _Included_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
#define _Included_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_CreateDepthSensor
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)LNuitrackJavaWrapper/Types/Exceptions/NuitrackExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1CreateDepthSensor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_DestroyDepthSensor
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1DestroyDepthSensor
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_OnDepthSensorUpdate
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;LNuitrackJavaWrapper/Native/Callbacks/DepthSensorCallbackInterface;)J
 */
JNIEXPORT jlong JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1OnDepthSensorUpdate
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_OnDepthSensorUpdateDisconnect
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;J)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1OnDepthSensorUpdateDisconnect
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_GetDepthSensorData
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)LNuitrackJavaWrapper/Native/Pointers/DepthFramePtr;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1GetDepthSensorData
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_GetDepthSensorOutputMode
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;LNuitrackJavaWrapper/Native/ChangeableObject;)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1GetDepthSensorOutputMode
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_ctypes_ConvertProjToRealCoordsXYZ
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;JJJ)LNuitrackJavaWrapper/Types/Vector3;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1ctypes_1ConvertProjToRealCoordsXYZ
  (JNIEnv *, jclass, jobject, jlong, jlong, jlong);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_ctypes_ConvertProjToRealCoordsVector3
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;LNuitrackJavaWrapper/Types/Vector3;)LNuitrackJavaWrapper/Types/Vector3;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1ctypes_1ConvertProjToRealCoordsVector3
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_ctypes_ConvertRealToProjCoordsXYZ
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;FFF)LNuitrackJavaWrapper/Types/Vector3;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1ctypes_1ConvertRealToProjCoordsXYZ
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_ctypes_ConvertRealToProjCoordsVector3
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;LNuitrackJavaWrapper/Types/Vector3;)LNuitrackJavaWrapper/Types/Vector3;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1ctypes_1ConvertRealToProjCoordsVector3
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_IsDepthSensorMirror
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;)Z
 */
JNIEXPORT jboolean JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1IsDepthSensorMirror
  (JNIEnv *, jclass, jobject);

/*
 * Class:     NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_CAPI
 * Method:    nuitrack_SetDepthSensorMirror
 * Signature: (LNuitrackJavaWrapper/Native/Pointers/NuitrackModulePtr;Z)V
 */
JNIEXPORT void JNICALL Java_NuitrackJavaWrapper_Native_NuitrackImport_DepthSensor_1CAPI_nuitrack_1SetDepthSensorMirror
  (JNIEnv *, jclass, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
