/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NuitrackJavaWrapper_NuitrackImport */

#ifndef _Included_NuitrackJavaWrapper_NuitrackImport
#define _Included_NuitrackJavaWrapper_NuitrackImport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NuitrackJavaWrapper_NuitrackImport
 * Method:    nuitrack_Initialize
 * Signature: ()LNuitrackJavaWrapper/ExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_NuitrackImport_nuitrack_1Initialize
  (JNIEnv *, jobject);

/*
 * Class:     NuitrackJavaWrapper_NuitrackImport
 * Method:    nuitrack_InitializeFromConfig
 * Signature: (Ljava/lang/String;)LNuitrackJavaWrapper/ExceptionType;
 */
JNIEXPORT jobject JNICALL Java_NuitrackJavaWrapper_NuitrackImport_nuitrack_1InitializeFromConfig
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
